project:
  type: website
  output-dir: docs

website:
  title: "LivingDataLab"
  description: ''
  site-url: 'http://livingdatalab.com'
  twitter-card: true
  open-graph: true
  favicon: "favicon.ico"
  google-analytics: "UA-91568149-1"
  navbar:
    logo: "logo.png"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pranath
      - icon: twitter
        href: https://twitter.com/LivingDataLab
format:
  html:
    theme: flatly
    css: styles.css
