<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pranath Fernando">
<meta name="dcterms.date" content="2022-05-22">
<meta name="description" content="In this project we will be working with the results of the X-ray classification model for diseases we developed in the previous article, and evaluate the model performance on each of these classes using various classification metrics.">

<title>LivingDataLab - Evaluating Healthcare Diagnostic Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-91568149-1', 'auto');

ga('send', {
  hitType: 'pageview',
  'anonymizeIp': true,
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="LivingDataLab - Evaluating Healthcare Diagnostic Models">
<meta property="og:description" content="In this project we will be working with the results of the X-ray classification model for diseases we developed in the previous article, and evaluate the model performance on each of these classes…">
<meta property="og:image" content="https://github.com/pranath/blog/raw/master/images/ai_health.jpg">
<meta property="og:site-name" content="LivingDataLab">
<meta name="twitter:title" content="LivingDataLab - Evaluating Healthcare Diagnostic Models">
<meta name="twitter:description" content="In this project we will be working with the results of the X-ray classification model for diseases we developed in the previous article, and evaluate the model performance on each of these classes…">
<meta name="twitter:image" content="https://github.com/pranath/blog/raw/master/images/ai_health.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">LivingDataLab</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pranath"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/LivingDataLab"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Evaluating Healthcare Diagnostic Models</h1>
                  <div>
        <div class="description">
          In this project we will be working with the results of the X-ray classification model for diseases we developed in the previous article, and evaluate the model performance on each of these classes using various classification metrics.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">health</div>
                <div class="quarto-category">deep-learning</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Pranath Fernando </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 22, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">1</span>  Introduction</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="toc-section-number">2</span>  Overview</a></li>
  <li><a href="#metrics" id="toc-metrics" class="nav-link" data-scroll-target="#metrics"><span class="toc-section-number">3</span>  Metrics</a>
  <ul class="collapse">
  <li><a href="#true-positives-false-positives-true-negatives-and-false-negatives" id="toc-true-positives-false-positives-true-negatives-and-false-negatives" class="nav-link" data-scroll-target="#true-positives-false-positives-true-negatives-and-false-negatives"><span class="toc-section-number">3.1</span>  True Positives, False Positives, True Negatives and False Negatives</a></li>
  <li><a href="#accuracy" id="toc-accuracy" class="nav-link" data-scroll-target="#accuracy"><span class="toc-section-number">3.2</span>  Accuracy</a></li>
  <li><a href="#prevalence" id="toc-prevalence" class="nav-link" data-scroll-target="#prevalence"><span class="toc-section-number">3.3</span>  Prevalence</a></li>
  <li><a href="#sensitivity-and-specificity" id="toc-sensitivity-and-specificity" class="nav-link" data-scroll-target="#sensitivity-and-specificity"><span class="toc-section-number">3.4</span>  Sensitivity and Specificity</a></li>
  <li><a href="#roc-curve" id="toc-roc-curve" class="nav-link" data-scroll-target="#roc-curve"><span class="toc-section-number">3.5</span>  ROC Curve</a></li>
  </ul></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="toc-section-number">4</span>  Confidence Intervals</a></li>
  <li><a href="#precision-recall-curve" id="toc-precision-recall-curve" class="nav-link" data-scroll-target="#precision-recall-curve"><span class="toc-section-number">5</span>  Precision-Recall Curve</a></li>
  <li><a href="#f1-score" id="toc-f1-score" class="nav-link" data-scroll-target="#f1-score"><span class="toc-section-number">6</span>  F1 Score</a></li>
  <li><a href="#calibration" id="toc-calibration" class="nav-link" data-scroll-target="#calibration"><span class="toc-section-number">7</span>  Calibration</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="toc-section-number">8</span>  Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>In my previous article <a href="2022-05-15-medical-diagnosis-chest-xrays.html">I developed a deep learning model able to classify 14 different diseases using chest x-rays</a>. There are various meterics available to help evaluate model performance, but there are specific metrics that are of particular relevance to evaluating models for medical diagnosis. These metrics which we will be covering in this article are:</p>
<ol type="1">
<li>Accuracy</li>
<li>Prevalence</li>
<li>Specificity &amp; Sensitivity</li>
<li>PPV and NPV</li>
<li>ROC curve and AUCROC (c-statistic)</li>
<li>Confidence Intervals</li>
</ol>
</section>
<section id="overview" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="overview"><span class="header-section-number">2</span> Overview</h2>
<p>Let’s take a look at our dataset. The data is stored in two CSV files called <code>train_preds.csv</code> and <code>valid_preds.csv</code>. We have precomputed the model outputs for our test cases. We’ll work with these predictions and the true class labels throughout this article.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>train_results <span class="op">=</span> pd.read_csv(<span class="st">"data/train_preds.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>valid_results <span class="op">=</span> pd.read_csv(<span class="st">"data/valid_preds.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># the labels in our dataset</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>class_labels <span class="op">=</span> [<span class="st">'Cardiomegaly'</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a> <span class="st">'Emphysema'</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a> <span class="st">'Effusion'</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a> <span class="st">'Hernia'</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a> <span class="st">'Infiltration'</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a> <span class="st">'Mass'</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a> <span class="st">'Nodule'</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a> <span class="st">'Atelectasis'</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a> <span class="st">'Pneumothorax'</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a> <span class="st">'Pleural_Thickening'</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a> <span class="st">'Pneumonia'</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a> <span class="st">'Fibrosis'</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a> <span class="st">'Edema'</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a> <span class="st">'Consolidation'</span>]</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># the labels for prediction values in our dataset</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>pred_labels <span class="op">=</span> [l <span class="op">+</span> <span class="st">"_pred"</span> <span class="cf">for</span> l <span class="kw">in</span> class_labels]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Extract the labels (y) and the predictions (pred).</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> valid_results[class_labels].values</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>pred <span class="op">=</span> valid_results[pred_labels].values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Run the next cell to view them side by side.</p>
<div class="cell" data-outputid="f521ab94-fb5d-4ba6-e8e4-8b0a0ca22863" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># let's take a peek at our dataset</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>valid_results[np.concatenate([class_labels, pred_labels])].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Cardiomegaly</th>
      <th>Emphysema</th>
      <th>Effusion</th>
      <th>Hernia</th>
      <th>Infiltration</th>
      <th>Mass</th>
      <th>Nodule</th>
      <th>Atelectasis</th>
      <th>Pneumothorax</th>
      <th>Pleural_Thickening</th>
      <th>...</th>
      <th>Infiltration_pred</th>
      <th>Mass_pred</th>
      <th>Nodule_pred</th>
      <th>Atelectasis_pred</th>
      <th>Pneumothorax_pred</th>
      <th>Pleural_Thickening_pred</th>
      <th>Pneumonia_pred</th>
      <th>Fibrosis_pred</th>
      <th>Edema_pred</th>
      <th>Consolidation_pred</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0.256020</td>
      <td>0.266928</td>
      <td>0.312440</td>
      <td>0.460342</td>
      <td>0.079453</td>
      <td>0.271495</td>
      <td>0.276861</td>
      <td>0.398799</td>
      <td>0.015867</td>
      <td>0.156320</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0.382199</td>
      <td>0.176825</td>
      <td>0.465807</td>
      <td>0.489424</td>
      <td>0.084595</td>
      <td>0.377318</td>
      <td>0.363582</td>
      <td>0.638024</td>
      <td>0.025948</td>
      <td>0.144419</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0.427727</td>
      <td>0.115513</td>
      <td>0.249030</td>
      <td>0.035105</td>
      <td>0.238761</td>
      <td>0.167095</td>
      <td>0.166389</td>
      <td>0.262463</td>
      <td>0.007758</td>
      <td>0.125790</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0.158596</td>
      <td>0.259460</td>
      <td>0.334870</td>
      <td>0.266489</td>
      <td>0.073371</td>
      <td>0.229834</td>
      <td>0.191281</td>
      <td>0.344348</td>
      <td>0.008559</td>
      <td>0.119153</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0.536762</td>
      <td>0.198797</td>
      <td>0.273110</td>
      <td>0.186771</td>
      <td>0.242122</td>
      <td>0.309786</td>
      <td>0.411771</td>
      <td>0.244666</td>
      <td>0.126930</td>
      <td>0.342409</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 28 columns</p>
</div>
</div>
</div>
<p>To further understand our dataset details, here’s a histogram of the number of samples for each label in the validation dataset:</p>
<div class="cell" data-outputid="3780bec9-f9da-4e6f-a775-35db3c91af45" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>plt.bar(x <span class="op">=</span> class_labels, height<span class="op">=</span> y.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">0</span>))<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-05-22-evaluation-diagnostic-medical-models_files/figure-html/cell-6-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>It seem like our dataset has an imbalanced population of samples. Specifically, our dataset has a small number of patients diagnosed with a <code>Hernia</code>.</p>
</section>
<section id="metrics" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metrics"><span class="header-section-number">3</span> Metrics</h2>
<section id="true-positives-false-positives-true-negatives-and-false-negatives" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="true-positives-false-positives-true-negatives-and-false-negatives"><span class="header-section-number">3.1</span> True Positives, False Positives, True Negatives and False Negatives</h3>
<p>The most basic statistics to compute from the model predictions are the true positives, true negatives, false positives, and false negatives.</p>
<p>As the name suggests - True Positive (TP): The model classifies the example as positive, and the actual label also positive. - False Positive (FP): The model classifies the example as positive, <strong>but</strong> the actual label is negative. - True Negative (TN): The model classifies the example as negative, and the actual label is also negative. - False Negative (FN): The model classifies the example as negative, <strong>but</strong> the label is actually positive.</p>
<p>We will count the number of TP, FP, TN and FN in the given data. All of our metrics can be built off of these four statistics.</p>
<p>Recall that the model outputs real numbers between 0 and 1. * To compute binary class predictions, we need to convert these to either 0 or 1. * We’ll do this using a threshold value <span class="math inline">\(th\)</span>. * Any model outputs above <span class="math inline">\(th\)</span> are set to 1, and below <span class="math inline">\(th\)</span> are set to 0.</p>
<p>All of our metrics (except for AUC at the end) will depend on the choice of this threshold.</p>
<p>Let’s define some functions for computing each of these basic statistics.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> true_positives(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Count true positives.</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">        TP (int): true positives</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    TP <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get thresholded predictions</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    thresholded_preds <span class="op">=</span> pred <span class="op">&gt;=</span> th</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># compute TP</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    TP <span class="op">=</span> np.<span class="bu">sum</span>((y <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (thresholded_preds <span class="op">==</span> <span class="dv">1</span>))</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> TP</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> true_negatives(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co">    Count true negatives.</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="co">        TN (int): true negatives</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>    TN <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get thresholded predictions</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    thresholded_preds <span class="op">=</span> pred <span class="op">&gt;=</span> th</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># compute TN</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>    TN <span class="op">=</span> np.<span class="bu">sum</span>((y <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (thresholded_preds <span class="op">==</span> <span class="dv">0</span>))</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> TN</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> false_positives(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a><span class="co">    Count false positives.</span></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a><span class="co">        FP (int): false positives</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>    FP <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get thresholded predictions</span></span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>    thresholded_preds <span class="op">=</span> pred <span class="op">&gt;=</span> th</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>    <span class="co"># compute FP</span></span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>    FP <span class="op">=</span> np.<span class="bu">sum</span>((y <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (thresholded_preds <span class="op">==</span> <span class="dv">1</span>))</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> FP</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> false_negatives(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a><span class="co">    Count false positives.</span></span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a><span class="co">        FN (int): false negatives</span></span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a>    FN <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get thresholded predictions</span></span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a>    thresholded_preds <span class="op">=</span> pred <span class="op">&gt;=</span> th</span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a>    <span class="co"># compute FN</span></span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a>    FN <span class="op">=</span> np.<span class="bu">sum</span>((y <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (thresholded_preds <span class="op">==</span> <span class="dv">0</span>))</span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> FN</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="acc0073e-17b3-458f-cdda-f99a26ac1b02" data-execution_count="9">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test functions </span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>get_tp_tn_fp_fn_test(true_positives, true_negatives, false_positives, false_negatives)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>y_test</th>
      <th>preds_test</th>
      <th>category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>0.8</td>
      <td>TP</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>0.7</td>
      <td>TP</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>0.4</td>
      <td>TN</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>0.3</td>
      <td>TN</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>0.2</td>
      <td>TN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>0.5</td>
      <td>FP</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0</td>
      <td>0.6</td>
      <td>FP</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0</td>
      <td>0.7</td>
      <td>FP</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0</td>
      <td>0.8</td>
      <td>FP</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1</td>
      <td>0.1</td>
      <td>FN</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1</td>
      <td>0.2</td>
      <td>FN</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1</td>
      <td>0.3</td>
      <td>FN</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1</td>
      <td>0.4</td>
      <td>FN</td>
    </tr>
    <tr>
      <th>13</th>
      <td>1</td>
      <td>0.0</td>
      <td>FN</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Your functions calcualted: 
    TP: 2
    TN: 3
    FP: 4
    FN: 5
    
 All tests passed.
 All tests passed.
 All tests passed.
 All tests passed.</code></pre>
</div>
</div>
<section id="expected-output" class="level5">
<h5 class="anchored" data-anchor-id="expected-output">Expected output</h5>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Your functions calcualted: </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    TP: <span class="dv">2</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    TN: <span class="dv">3</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    FP: <span class="dv">4</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    FN: <span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code> All tests passed.
 All tests passed.
 All tests passed.
 All tests passed.</code></pre>
<div class="cell" data-outputid="52807e22-3463-46f8-c03b-92097b10ae0d" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Add these to a table for each disease</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>util.get_performance_metrics(y, pred, class_labels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>TP</th>
      <th>TN</th>
      <th>FP</th>
      <th>FN</th>
      <th>Accuracy</th>
      <th>Prevalence</th>
      <th>Sensitivity</th>
      <th>Specificity</th>
      <th>PPV</th>
      <th>NPV</th>
      <th>AUC</th>
      <th>F1</th>
      <th>Threshold</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cardiomegaly</th>
      <td>16</td>
      <td>814</td>
      <td>169</td>
      <td>1</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Emphysema</th>
      <td>20</td>
      <td>869</td>
      <td>103</td>
      <td>8</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Effusion</th>
      <td>99</td>
      <td>690</td>
      <td>196</td>
      <td>15</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Hernia</th>
      <td>1</td>
      <td>743</td>
      <td>255</td>
      <td>1</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Infiltration</th>
      <td>114</td>
      <td>543</td>
      <td>265</td>
      <td>78</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Mass</th>
      <td>40</td>
      <td>789</td>
      <td>158</td>
      <td>13</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Nodule</th>
      <td>28</td>
      <td>731</td>
      <td>220</td>
      <td>21</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Atelectasis</th>
      <td>64</td>
      <td>657</td>
      <td>249</td>
      <td>30</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumothorax</th>
      <td>24</td>
      <td>785</td>
      <td>183</td>
      <td>8</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pleural_Thickening</th>
      <td>24</td>
      <td>713</td>
      <td>259</td>
      <td>4</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumonia</th>
      <td>14</td>
      <td>661</td>
      <td>320</td>
      <td>5</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Fibrosis</th>
      <td>10</td>
      <td>725</td>
      <td>261</td>
      <td>4</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Edema</th>
      <td>15</td>
      <td>767</td>
      <td>213</td>
      <td>5</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Consolidation</th>
      <td>36</td>
      <td>658</td>
      <td>297</td>
      <td>9</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Right now it only has TP, TN, FP, FN. Throughout this article we’ll fill in all the other metrics to learn more about our model performance.</p>
</section>
</section>
<section id="accuracy" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="accuracy"><span class="header-section-number">3.2</span> Accuracy</h3>
<p>Let’s use a threshold of .5 for the probability cutoff for our predictions for all classes and calculate our model’s accuracy as we would normally do in a machine learning problem.</p>
<p><span class="math display">\[accuracy = \frac{\text{true positives} + \text{true negatives}}{\text{true positives} + \text{true negatives} + \text{false positives} + \text{false negatives}}\]</span></p>
<p>Let’s define a function to calculate this.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_accuracy(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute accuracy of predictions at threshold.</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">        accuracy (float): accuracy of predictions at threshold</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    accuracy <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get TP, FP, TN, FN using our previously defined functions</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    TP <span class="op">=</span> true_positives(y, pred, th)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    FP <span class="op">=</span> false_positives(y, pred, th)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    TN <span class="op">=</span> true_negatives(y, pred, th)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    FN <span class="op">=</span> false_negatives(y, pred, th)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute accuracy using TP, FP, TN, FN</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    accuracy <span class="op">=</span> (TP <span class="op">+</span> TN) <span class="op">/</span> (TP <span class="op">+</span> FP <span class="op">+</span> TN <span class="op">+</span> FN)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="a2a37bdc-7ef4-4824-9ea2-9678f6b0ccfb" data-execution_count="16">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test function</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>get_accuracy_test(get_accuracy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Case:

Test Labels:       [1 0 0 1 1]
Test Predictions:  [0.8 0.8 0.4 0.6 0.3]
Threshold:     0.5
Computed Accuracy: 0.6 

 All tests passed.</code></pre>
</div>
</div>
<section id="expected-output-1" class="level4">
<h4 class="anchored" data-anchor-id="expected-output-1">Expected output:</h4>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Test Case:</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>Test Labels:       [<span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span>]</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>Test Predictions:  [<span class="fl">0.8</span> <span class="fl">0.8</span> <span class="fl">0.4</span> <span class="fl">0.6</span> <span class="fl">0.3</span>]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>Threshold:       <span class="fl">0.5</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>Computed Accuracy: <span class="fl">0.6</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code> All tests passed.</code></pre>
<p>Let’s compute this for each disease.</p>
<div class="cell" data-outputid="7210644a-5bd9-4862-ca2b-4475f23e4515" data-execution_count="17">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>util.get_performance_metrics(y, pred, class_labels, acc<span class="op">=</span>get_accuracy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>TP</th>
      <th>TN</th>
      <th>FP</th>
      <th>FN</th>
      <th>Accuracy</th>
      <th>Prevalence</th>
      <th>Sensitivity</th>
      <th>Specificity</th>
      <th>PPV</th>
      <th>NPV</th>
      <th>AUC</th>
      <th>F1</th>
      <th>Threshold</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cardiomegaly</th>
      <td>16</td>
      <td>814</td>
      <td>169</td>
      <td>1</td>
      <td>0.83</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Emphysema</th>
      <td>20</td>
      <td>869</td>
      <td>103</td>
      <td>8</td>
      <td>0.889</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Effusion</th>
      <td>99</td>
      <td>690</td>
      <td>196</td>
      <td>15</td>
      <td>0.789</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Hernia</th>
      <td>1</td>
      <td>743</td>
      <td>255</td>
      <td>1</td>
      <td>0.744</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Infiltration</th>
      <td>114</td>
      <td>543</td>
      <td>265</td>
      <td>78</td>
      <td>0.657</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Mass</th>
      <td>40</td>
      <td>789</td>
      <td>158</td>
      <td>13</td>
      <td>0.829</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Nodule</th>
      <td>28</td>
      <td>731</td>
      <td>220</td>
      <td>21</td>
      <td>0.759</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Atelectasis</th>
      <td>64</td>
      <td>657</td>
      <td>249</td>
      <td>30</td>
      <td>0.721</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumothorax</th>
      <td>24</td>
      <td>785</td>
      <td>183</td>
      <td>8</td>
      <td>0.809</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pleural_Thickening</th>
      <td>24</td>
      <td>713</td>
      <td>259</td>
      <td>4</td>
      <td>0.737</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumonia</th>
      <td>14</td>
      <td>661</td>
      <td>320</td>
      <td>5</td>
      <td>0.675</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Fibrosis</th>
      <td>10</td>
      <td>725</td>
      <td>261</td>
      <td>4</td>
      <td>0.735</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Edema</th>
      <td>15</td>
      <td>767</td>
      <td>213</td>
      <td>5</td>
      <td>0.782</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Consolidation</th>
      <td>36</td>
      <td>658</td>
      <td>297</td>
      <td>9</td>
      <td>0.694</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>If we were to judge our model’s performance based on the accuracy metric, we would say that our model is not very accurate for detecting the <code>Infiltration</code> cases (accuracy of 0.657) but pretty accurate for detecting <code>Emphysema</code> (accuracy of 0.889).</p>
<p><strong>But is that really the case?…</strong></p>
<p>Let’s imagine a model that simply predicts that any patient does <strong>Not</strong> have <code>Emphysema</code>, regardless of patient’s measurements. Let’s calculate the accuracy for such a model.</p>
<div class="cell" data-outputid="840e3863-17e1-4905-9575-a7fd73367137" data-execution_count="18">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>get_accuracy(valid_results[<span class="st">"Emphysema"</span>].values, np.zeros(<span class="bu">len</span>(valid_results)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>0.972</code></pre>
</div>
</div>
<p>As you can see above, such a model would be 97% accurate! Even better than our deep learning based model.</p>
<p>But is this really a good model? Wouldn’t this model be wrong 100% of the time if the patient actually had this condition?</p>
<p>This issue can be particularly common in cases where we have very imbalanced classes and few examples of a particular disease, in such cases accuracy can be very misleading for what we want to know.</p>
<p>In the following sections, we will address this concern with more advanced model measures - <strong>sensitivity and specificity</strong> - that evaluate how well the model predicts positives for patients with the condition and negatives for cases that actually do not have the condition.</p>
</section>
</section>
<section id="prevalence" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="prevalence"><span class="header-section-number">3.3</span> Prevalence</h3>
<p>Another important concept is <strong>prevalence</strong>. * In a medical context, prevalence is the proportion of people in the population who have the disease (or condition, etc). * In machine learning terms, this is the proportion of positive examples.</p>
<p>We encountered prevalence in a <a href="https://livingdatalab.com/health/epidemiology/2022/02/22/measuring-disease-in-epidemiology.html">previous article on measures of disease in epidemiology</a>.</p>
<p>The expression for prevalence is:</p>
<p><span class="math display">\[prevalence = \frac{1}{N} \sum_{i} y_i\]</span></p>
<p>where <span class="math inline">\(y_i = 1\)</span> when the example is ‘positive’ (has the disease).</p>
<p>Let’s define a function to measure prevalence for each disease.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_prevalence(y):</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute prevalence.</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co">        prevalence (float): prevalence of positive cases</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    prevalence <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    prevalence <span class="op">=</span> np.<span class="bu">sum</span>(y) <span class="op">/</span> y.size</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> prevalence</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="a3888472-26c5-4340-e310-026d98a5fe2d" data-execution_count="20">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test function</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>get_prevalence_test(get_prevalence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Case:

Test Labels:          [1 0 0 1 1 0 0 0 0 1]
Computed Prevalence:  0.4 

 All tests passed.</code></pre>
</div>
</div>
<section id="expected-output-2" class="level4">
<h4 class="anchored" data-anchor-id="expected-output-2">Expected output:</h4>
<div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>Test Case:</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>Test Labels:          [<span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span>]</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>Computed Prevalence:  <span class="fl">0.4</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code> All tests passed.</code></pre>
<div class="cell" data-outputid="d9ce79fb-8222-43bf-fcef-1e3fdbbc8d66" data-execution_count="21">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate this for each disease</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>util.get_performance_metrics(y, pred, class_labels, acc<span class="op">=</span>get_accuracy, prevalence<span class="op">=</span>get_prevalence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>TP</th>
      <th>TN</th>
      <th>FP</th>
      <th>FN</th>
      <th>Accuracy</th>
      <th>Prevalence</th>
      <th>Sensitivity</th>
      <th>Specificity</th>
      <th>PPV</th>
      <th>NPV</th>
      <th>AUC</th>
      <th>F1</th>
      <th>Threshold</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cardiomegaly</th>
      <td>16</td>
      <td>814</td>
      <td>169</td>
      <td>1</td>
      <td>0.83</td>
      <td>0.017</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Emphysema</th>
      <td>20</td>
      <td>869</td>
      <td>103</td>
      <td>8</td>
      <td>0.889</td>
      <td>0.028</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Effusion</th>
      <td>99</td>
      <td>690</td>
      <td>196</td>
      <td>15</td>
      <td>0.789</td>
      <td>0.114</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Hernia</th>
      <td>1</td>
      <td>743</td>
      <td>255</td>
      <td>1</td>
      <td>0.744</td>
      <td>0.002</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Infiltration</th>
      <td>114</td>
      <td>543</td>
      <td>265</td>
      <td>78</td>
      <td>0.657</td>
      <td>0.192</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Mass</th>
      <td>40</td>
      <td>789</td>
      <td>158</td>
      <td>13</td>
      <td>0.829</td>
      <td>0.053</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Nodule</th>
      <td>28</td>
      <td>731</td>
      <td>220</td>
      <td>21</td>
      <td>0.759</td>
      <td>0.049</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Atelectasis</th>
      <td>64</td>
      <td>657</td>
      <td>249</td>
      <td>30</td>
      <td>0.721</td>
      <td>0.094</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumothorax</th>
      <td>24</td>
      <td>785</td>
      <td>183</td>
      <td>8</td>
      <td>0.809</td>
      <td>0.032</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pleural_Thickening</th>
      <td>24</td>
      <td>713</td>
      <td>259</td>
      <td>4</td>
      <td>0.737</td>
      <td>0.028</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumonia</th>
      <td>14</td>
      <td>661</td>
      <td>320</td>
      <td>5</td>
      <td>0.675</td>
      <td>0.019</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Fibrosis</th>
      <td>10</td>
      <td>725</td>
      <td>261</td>
      <td>4</td>
      <td>0.735</td>
      <td>0.014</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Edema</th>
      <td>15</td>
      <td>767</td>
      <td>213</td>
      <td>5</td>
      <td>0.782</td>
      <td>0.02</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Consolidation</th>
      <td>36</td>
      <td>658</td>
      <td>297</td>
      <td>9</td>
      <td>0.694</td>
      <td>0.045</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p><code>Hernia</code> has a prevalence 0.002, which is the rarest among the studied conditions in our dataset.</p>
</section>
</section>
<section id="sensitivity-and-specificity" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="sensitivity-and-specificity"><span class="header-section-number">3.4</span> Sensitivity and Specificity</h3>
<p><img src="https://github.com/pranath/blog/raw/master/images/sens_spec.png" title="Sensitivity and Specificity" class="img-fluid"></p>
<p>Sensitivity and specificity are two of the most prominent numbers that are used to measure diagnostics tests. - Sensitivity is the probability that our test outputs positive given that the case is actually positive. - Specificity is the probability that the test outputs negative given that the case is actually negative.</p>
<p>We can phrase this easily in terms of true positives, true negatives, false positives, and false negatives:</p>
<p><span class="math display">\[sensitivity = \frac{\text{true positives}}{\text{true positives} + \text{false negatives}}\]</span></p>
<p><span class="math display">\[specificity = \frac{\text{true negatives}}{\text{true negatives} + \text{false positives}}\]</span></p>
<p>Let’s calculate sensitivity and specificity for our model.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_sensitivity(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute sensitivity of predictions at threshold.</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co">        sensitivity (float): probability that our test outputs positive given that the case is actually positive</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    sensitivity <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get TP and FN using our previously defined functions</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    TP <span class="op">=</span> true_positives(y, pred, th)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    FN <span class="op">=</span> false_negatives(y, pred, th)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># use TP and FN to compute sensitivity</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>    sensitivity <span class="op">=</span> TP <span class="op">/</span> (TP <span class="op">+</span> FN)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> sensitivity</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_specificity(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute specificity of predictions at threshold.</span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a><span class="co">        specificity (float): probability that the test outputs negative given that the case is actually negative</span></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>    specificity <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get TN and FP using our previously defined functions</span></span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>    TN <span class="op">=</span> true_negatives(y, pred, th)</span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>    FP <span class="op">=</span> false_positives(y, pred, th)</span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># use TN and FP to compute specificity </span></span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>    specificity <span class="op">=</span> TN <span class="op">/</span> (TN <span class="op">+</span> FP)</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> specificity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="1915ff27-1701-4ee7-ddf7-5a058faee29c" data-execution_count="23">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test function</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>get_sensitivity_specificity_test(get_sensitivity, get_specificity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Case:

Test Labels:           [1 0 0 1 1]
Test Predictions:      [1 0 0 1 1]
Threshold:         0.5
Computed Sensitivity:  0.6666666666666666
Computed Specificity:  0.5 

 All tests passed.
 All tests passed.</code></pre>
</div>
</div>
<section id="expected-output-3" class="level4">
<h4 class="anchored" data-anchor-id="expected-output-3">Expected output:</h4>
<div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>Test Case:</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>Test Labels:           [<span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span>]</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>Test Predictions:      [<span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span>]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>Threshold:           <span class="fl">0.5</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>Computed Sensitivity:  <span class="fl">0.6666666666666666</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>Computed Specificity:  <span class="fl">0.5</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code> All tests passed.
 All tests passed.
</code></pre>
<div class="cell" data-outputid="1f82e534-0353-406e-df6a-b5926db06803" data-execution_count="24">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate for all diseases</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>util.get_performance_metrics(y, pred, class_labels, acc<span class="op">=</span>get_accuracy, prevalence<span class="op">=</span>get_prevalence, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                        sens<span class="op">=</span>get_sensitivity, spec<span class="op">=</span>get_specificity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>TP</th>
      <th>TN</th>
      <th>FP</th>
      <th>FN</th>
      <th>Accuracy</th>
      <th>Prevalence</th>
      <th>Sensitivity</th>
      <th>Specificity</th>
      <th>PPV</th>
      <th>NPV</th>
      <th>AUC</th>
      <th>F1</th>
      <th>Threshold</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cardiomegaly</th>
      <td>16</td>
      <td>814</td>
      <td>169</td>
      <td>1</td>
      <td>0.83</td>
      <td>0.017</td>
      <td>0.941</td>
      <td>0.828</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Emphysema</th>
      <td>20</td>
      <td>869</td>
      <td>103</td>
      <td>8</td>
      <td>0.889</td>
      <td>0.028</td>
      <td>0.714</td>
      <td>0.894</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Effusion</th>
      <td>99</td>
      <td>690</td>
      <td>196</td>
      <td>15</td>
      <td>0.789</td>
      <td>0.114</td>
      <td>0.868</td>
      <td>0.779</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Hernia</th>
      <td>1</td>
      <td>743</td>
      <td>255</td>
      <td>1</td>
      <td>0.744</td>
      <td>0.002</td>
      <td>0.5</td>
      <td>0.744</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Infiltration</th>
      <td>114</td>
      <td>543</td>
      <td>265</td>
      <td>78</td>
      <td>0.657</td>
      <td>0.192</td>
      <td>0.594</td>
      <td>0.672</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Mass</th>
      <td>40</td>
      <td>789</td>
      <td>158</td>
      <td>13</td>
      <td>0.829</td>
      <td>0.053</td>
      <td>0.755</td>
      <td>0.833</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Nodule</th>
      <td>28</td>
      <td>731</td>
      <td>220</td>
      <td>21</td>
      <td>0.759</td>
      <td>0.049</td>
      <td>0.571</td>
      <td>0.769</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Atelectasis</th>
      <td>64</td>
      <td>657</td>
      <td>249</td>
      <td>30</td>
      <td>0.721</td>
      <td>0.094</td>
      <td>0.681</td>
      <td>0.725</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumothorax</th>
      <td>24</td>
      <td>785</td>
      <td>183</td>
      <td>8</td>
      <td>0.809</td>
      <td>0.032</td>
      <td>0.75</td>
      <td>0.811</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pleural_Thickening</th>
      <td>24</td>
      <td>713</td>
      <td>259</td>
      <td>4</td>
      <td>0.737</td>
      <td>0.028</td>
      <td>0.857</td>
      <td>0.734</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumonia</th>
      <td>14</td>
      <td>661</td>
      <td>320</td>
      <td>5</td>
      <td>0.675</td>
      <td>0.019</td>
      <td>0.737</td>
      <td>0.674</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Fibrosis</th>
      <td>10</td>
      <td>725</td>
      <td>261</td>
      <td>4</td>
      <td>0.735</td>
      <td>0.014</td>
      <td>0.714</td>
      <td>0.735</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Edema</th>
      <td>15</td>
      <td>767</td>
      <td>213</td>
      <td>5</td>
      <td>0.782</td>
      <td>0.02</td>
      <td>0.75</td>
      <td>0.783</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Consolidation</th>
      <td>36</td>
      <td>658</td>
      <td>297</td>
      <td>9</td>
      <td>0.694</td>
      <td>0.045</td>
      <td>0.8</td>
      <td>0.689</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Note that specificity and sensitivity do not depend on the prevalence of the positive class in the dataset. * This is because the statistics are only computed within people of the same class * Sensitivity only considers output on people in the positive class * Similarly, specificity only considers output on people in the negative class.</p>
<p><a name="3-5"></a> ### PPV and NPV</p>
<p>Diagnostically, however, sensitivity and specificity are not helpful. Sensitivity, for example, tells us the probability our test outputs positive given that the person already has the condition. Here, we are conditioning on the thing we would like to find out (whether the patient has the condition)!</p>
<p>What would be more helpful is the probability that the person has the disease given that our test outputs positive. That brings us to positive predictive value (PPV) and negative predictive value (NPV).</p>
<ul>
<li>Positive predictive value (PPV) is the probability that subjects with a positive screening test truly have the disease.</li>
<li>Negative predictive value (NPV) is the probability that subjects with a negative screening test truly don’t have the disease.</li>
</ul>
<p>Again, we can formulate these in terms of true positives, true negatives, false positives, and false negatives:</p>
<p><span class="math display">\[PPV = \frac{\text{true positives}}{\text{true positives} + \text{false positives}}\]</span></p>
<p><span class="math display">\[NPV = \frac{\text{true negatives}}{\text{true negatives} + \text{false negatives}}\]</span></p>
<p>We also encountered PPV and NPV in a <a href="2022-02-22-measuring-disease-in-epidemiology.html">previous article on measures of disease in epidemiology</a>.</p>
<p>Let’s calculate PPV &amp; NPV for our model.</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_ppv(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute PPV of predictions at threshold.</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co">        PPV (float): positive predictive value of predictions at threshold</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    PPV <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get TP and FP using our previously defined functions</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    TP <span class="op">=</span> true_positives(y, pred, th)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    FP <span class="op">=</span> false_positives(y, pred, th)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># use TP and FP to compute PPV</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    PPV <span class="op">=</span> TP <span class="op">/</span> (TP <span class="op">+</span> FP)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> PPV</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_npv(y, pred, th<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute NPV of predictions at threshold.</span></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a><span class="co">        y (np.array): ground truth, size (n_examples)</span></span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a><span class="co">        pred (np.array): model output, size (n_examples)</span></span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a><span class="co">        th (float): cutoff value for positive prediction from model</span></span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a><span class="co">        NPV (float): negative predictive value of predictions at threshold</span></span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>    NPV <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get TN and FN using our previously defined functions</span></span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a>    TN <span class="op">=</span> true_negatives(y, pred, th)</span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a>    FN <span class="op">=</span> false_negatives(y, pred, th)</span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-41"><a href="#cb31-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># use TN and FN to compute NPV</span></span>
<span id="cb31-42"><a href="#cb31-42" aria-hidden="true" tabindex="-1"></a>    NPV <span class="op">=</span> TN <span class="op">/</span> (TN <span class="op">+</span> FN)</span>
<span id="cb31-43"><a href="#cb31-43" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb31-44"><a href="#cb31-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> NPV</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="e9759c8f-17ef-47df-c612-d7c3b46970ab" data-execution_count="26">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test function</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>get_ppv_npv_test(get_ppv, get_npv)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test Case:

Test Labels:       [1 0 0 1 1]
Test Predictions:  [1 0 0 1 1]
Threshold:     0.5
Computed PPV:      0.6666666666666666
Computed NPV:      0.5 

 All tests passed.
 All tests passed.</code></pre>
</div>
</div>
</section>
<section id="expected-output-4" class="level4">
<h4 class="anchored" data-anchor-id="expected-output-4">Expected output:</h4>
<div class="sourceCode" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>Test Case:</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>Test Labels:       [<span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span>]</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>Test Predictions:  [<span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span>]</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>Threshold:       <span class="fl">0.5</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>Computed PPV:     <span class="fl">0.6666666666666666</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>Computed NPV:     <span class="fl">0.5</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code> All tests passed.
 All tests passed.</code></pre>
<div class="cell" data-outputid="e8fe9db4-f7a3-4403-c36e-60cfb84385c3" data-execution_count="27">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate for all diseases</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>util.get_performance_metrics(y, pred, class_labels, acc<span class="op">=</span>get_accuracy, prevalence<span class="op">=</span>get_prevalence, </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                        sens<span class="op">=</span>get_sensitivity, spec<span class="op">=</span>get_specificity, ppv<span class="op">=</span>get_ppv, npv<span class="op">=</span>get_npv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>TP</th>
      <th>TN</th>
      <th>FP</th>
      <th>FN</th>
      <th>Accuracy</th>
      <th>Prevalence</th>
      <th>Sensitivity</th>
      <th>Specificity</th>
      <th>PPV</th>
      <th>NPV</th>
      <th>AUC</th>
      <th>F1</th>
      <th>Threshold</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cardiomegaly</th>
      <td>16</td>
      <td>814</td>
      <td>169</td>
      <td>1</td>
      <td>0.83</td>
      <td>0.017</td>
      <td>0.941</td>
      <td>0.828</td>
      <td>0.086</td>
      <td>0.999</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Emphysema</th>
      <td>20</td>
      <td>869</td>
      <td>103</td>
      <td>8</td>
      <td>0.889</td>
      <td>0.028</td>
      <td>0.714</td>
      <td>0.894</td>
      <td>0.163</td>
      <td>0.991</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Effusion</th>
      <td>99</td>
      <td>690</td>
      <td>196</td>
      <td>15</td>
      <td>0.789</td>
      <td>0.114</td>
      <td>0.868</td>
      <td>0.779</td>
      <td>0.336</td>
      <td>0.979</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Hernia</th>
      <td>1</td>
      <td>743</td>
      <td>255</td>
      <td>1</td>
      <td>0.744</td>
      <td>0.002</td>
      <td>0.5</td>
      <td>0.744</td>
      <td>0.004</td>
      <td>0.999</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Infiltration</th>
      <td>114</td>
      <td>543</td>
      <td>265</td>
      <td>78</td>
      <td>0.657</td>
      <td>0.192</td>
      <td>0.594</td>
      <td>0.672</td>
      <td>0.301</td>
      <td>0.874</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Mass</th>
      <td>40</td>
      <td>789</td>
      <td>158</td>
      <td>13</td>
      <td>0.829</td>
      <td>0.053</td>
      <td>0.755</td>
      <td>0.833</td>
      <td>0.202</td>
      <td>0.984</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Nodule</th>
      <td>28</td>
      <td>731</td>
      <td>220</td>
      <td>21</td>
      <td>0.759</td>
      <td>0.049</td>
      <td>0.571</td>
      <td>0.769</td>
      <td>0.113</td>
      <td>0.972</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Atelectasis</th>
      <td>64</td>
      <td>657</td>
      <td>249</td>
      <td>30</td>
      <td>0.721</td>
      <td>0.094</td>
      <td>0.681</td>
      <td>0.725</td>
      <td>0.204</td>
      <td>0.956</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumothorax</th>
      <td>24</td>
      <td>785</td>
      <td>183</td>
      <td>8</td>
      <td>0.809</td>
      <td>0.032</td>
      <td>0.75</td>
      <td>0.811</td>
      <td>0.116</td>
      <td>0.99</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pleural_Thickening</th>
      <td>24</td>
      <td>713</td>
      <td>259</td>
      <td>4</td>
      <td>0.737</td>
      <td>0.028</td>
      <td>0.857</td>
      <td>0.734</td>
      <td>0.085</td>
      <td>0.994</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumonia</th>
      <td>14</td>
      <td>661</td>
      <td>320</td>
      <td>5</td>
      <td>0.675</td>
      <td>0.019</td>
      <td>0.737</td>
      <td>0.674</td>
      <td>0.042</td>
      <td>0.992</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Fibrosis</th>
      <td>10</td>
      <td>725</td>
      <td>261</td>
      <td>4</td>
      <td>0.735</td>
      <td>0.014</td>
      <td>0.714</td>
      <td>0.735</td>
      <td>0.037</td>
      <td>0.995</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Edema</th>
      <td>15</td>
      <td>767</td>
      <td>213</td>
      <td>5</td>
      <td>0.782</td>
      <td>0.02</td>
      <td>0.75</td>
      <td>0.783</td>
      <td>0.066</td>
      <td>0.994</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Consolidation</th>
      <td>36</td>
      <td>658</td>
      <td>297</td>
      <td>9</td>
      <td>0.694</td>
      <td>0.045</td>
      <td>0.8</td>
      <td>0.689</td>
      <td>0.108</td>
      <td>0.987</td>
      <td>Not Defined</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Notice that despite having very high sensitivity and accuracy, the PPV of the predictions could still be very low.</p>
<p>This is the case with <code>Edema</code>, for example. * The sensitivity for <code>Edema</code> is 0.75. * However, given that the model predicted positive, the probability that a person has Edema (its PPV) is only 0.066!</p>
</section>
</section>
<section id="roc-curve" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="roc-curve"><span class="header-section-number">3.5</span> ROC Curve</h3>
<p>So far we have been operating under the assumption that our model’s prediction of <code>0.5</code> and above should be treated as positive and otherwise it should be treated as negative. This however was a rather arbitrary choice. One way to see this, is to look at a very informative visualization called the receiver operating characteristic (ROC) curve.</p>
<p>The ROC curve is created by plotting the true positive rate (TPR) against the false positive rate (FPR) at various threshold settings. The ideal point is at the top left, with a true positive rate of 1 and a false positive rate of 0. The various points on the curve are generated by gradually changing the threshold.</p>
<p>Let’s look at this curve for our model:</p>
<div class="cell" data-outputid="66725978-cb15-4ade-c4da-33deca6c509d" data-execution_count="28">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>util.get_curve(y, pred, class_labels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-05-22-evaluation-diagnostic-medical-models_files/figure-html/cell-23-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The area under the ROC curve is also called AUCROC or C-statistic and is a measure of goodness of fit. In medical literature this number also gives the probability that a randomly selected patient who experienced a condition had a higher risk score than a patient who had not experienced the event. This summarizes the model output across all thresholds, and provides a good sense of the discriminative power of a given model.</p>
<p>One important caveat to bear in mind with the ROC curve is that it implicitly assumes roughly equal numbers of positive and negative cases for each disease. This is because the false positive rate includes true negatives in its calculation. For a disease with many examples without the disease and few with the disease - this could lead to a misleading indication of model performance. In such cases, the <strong>precision-recall curve</strong> can be a better indication of performance, which we will cover shortly.</p>
<p>Let’s use the <code>sklearn</code> metric function of <code>roc_auc_score</code> to add this score to our metrics table.</p>
<div class="cell" data-outputid="a249365b-c1a9-45d5-943b-a63880a25a38" data-execution_count="29">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> roc_auc_score</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>util.get_performance_metrics(y, pred, class_labels, acc<span class="op">=</span>get_accuracy, prevalence<span class="op">=</span>get_prevalence, </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                        sens<span class="op">=</span>get_sensitivity, spec<span class="op">=</span>get_specificity, ppv<span class="op">=</span>get_ppv, npv<span class="op">=</span>get_npv, auc<span class="op">=</span>roc_auc_score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>TP</th>
      <th>TN</th>
      <th>FP</th>
      <th>FN</th>
      <th>Accuracy</th>
      <th>Prevalence</th>
      <th>Sensitivity</th>
      <th>Specificity</th>
      <th>PPV</th>
      <th>NPV</th>
      <th>AUC</th>
      <th>F1</th>
      <th>Threshold</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cardiomegaly</th>
      <td>16</td>
      <td>814</td>
      <td>169</td>
      <td>1</td>
      <td>0.83</td>
      <td>0.017</td>
      <td>0.941</td>
      <td>0.828</td>
      <td>0.086</td>
      <td>0.999</td>
      <td>0.933</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Emphysema</th>
      <td>20</td>
      <td>869</td>
      <td>103</td>
      <td>8</td>
      <td>0.889</td>
      <td>0.028</td>
      <td>0.714</td>
      <td>0.894</td>
      <td>0.163</td>
      <td>0.991</td>
      <td>0.935</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Effusion</th>
      <td>99</td>
      <td>690</td>
      <td>196</td>
      <td>15</td>
      <td>0.789</td>
      <td>0.114</td>
      <td>0.868</td>
      <td>0.779</td>
      <td>0.336</td>
      <td>0.979</td>
      <td>0.891</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Hernia</th>
      <td>1</td>
      <td>743</td>
      <td>255</td>
      <td>1</td>
      <td>0.744</td>
      <td>0.002</td>
      <td>0.5</td>
      <td>0.744</td>
      <td>0.004</td>
      <td>0.999</td>
      <td>0.644</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Infiltration</th>
      <td>114</td>
      <td>543</td>
      <td>265</td>
      <td>78</td>
      <td>0.657</td>
      <td>0.192</td>
      <td>0.594</td>
      <td>0.672</td>
      <td>0.301</td>
      <td>0.874</td>
      <td>0.696</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Mass</th>
      <td>40</td>
      <td>789</td>
      <td>158</td>
      <td>13</td>
      <td>0.829</td>
      <td>0.053</td>
      <td>0.755</td>
      <td>0.833</td>
      <td>0.202</td>
      <td>0.984</td>
      <td>0.888</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Nodule</th>
      <td>28</td>
      <td>731</td>
      <td>220</td>
      <td>21</td>
      <td>0.759</td>
      <td>0.049</td>
      <td>0.571</td>
      <td>0.769</td>
      <td>0.113</td>
      <td>0.972</td>
      <td>0.745</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Atelectasis</th>
      <td>64</td>
      <td>657</td>
      <td>249</td>
      <td>30</td>
      <td>0.721</td>
      <td>0.094</td>
      <td>0.681</td>
      <td>0.725</td>
      <td>0.204</td>
      <td>0.956</td>
      <td>0.781</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumothorax</th>
      <td>24</td>
      <td>785</td>
      <td>183</td>
      <td>8</td>
      <td>0.809</td>
      <td>0.032</td>
      <td>0.75</td>
      <td>0.811</td>
      <td>0.116</td>
      <td>0.99</td>
      <td>0.826</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pleural_Thickening</th>
      <td>24</td>
      <td>713</td>
      <td>259</td>
      <td>4</td>
      <td>0.737</td>
      <td>0.028</td>
      <td>0.857</td>
      <td>0.734</td>
      <td>0.085</td>
      <td>0.994</td>
      <td>0.868</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumonia</th>
      <td>14</td>
      <td>661</td>
      <td>320</td>
      <td>5</td>
      <td>0.675</td>
      <td>0.019</td>
      <td>0.737</td>
      <td>0.674</td>
      <td>0.042</td>
      <td>0.992</td>
      <td>0.762</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Fibrosis</th>
      <td>10</td>
      <td>725</td>
      <td>261</td>
      <td>4</td>
      <td>0.735</td>
      <td>0.014</td>
      <td>0.714</td>
      <td>0.735</td>
      <td>0.037</td>
      <td>0.995</td>
      <td>0.801</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Edema</th>
      <td>15</td>
      <td>767</td>
      <td>213</td>
      <td>5</td>
      <td>0.782</td>
      <td>0.02</td>
      <td>0.75</td>
      <td>0.783</td>
      <td>0.066</td>
      <td>0.994</td>
      <td>0.856</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Consolidation</th>
      <td>36</td>
      <td>658</td>
      <td>297</td>
      <td>9</td>
      <td>0.694</td>
      <td>0.045</td>
      <td>0.8</td>
      <td>0.689</td>
      <td>0.108</td>
      <td>0.987</td>
      <td>0.799</td>
      <td>Not Defined</td>
      <td>0.5</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="confidence-intervals" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="confidence-intervals"><span class="header-section-number">4</span> Confidence Intervals</h2>
<p>Of course our dataset is only a sample of the real world, and our calculated values for all above metrics is an estimate of the real world values. It would be good to quantify this uncertainty due to the sampling of our dataset. We’ll do this through the use of confidence intervals. A 95% confidence interval for an estimate <span class="math inline">\(\hat{s}\)</span> of a parameter <span class="math inline">\(s\)</span> is an interval <span class="math inline">\(I = (a, b)\)</span> such that 95% of the time when the experiment is run, the true value <span class="math inline">\(s\)</span> is contained in <span class="math inline">\(I\)</span>. More concretely, if we were to run the experiment many times, then the fraction of those experiments for which <span class="math inline">\(I\)</span> contains the true parameter would tend towards 95%.</p>
<p>While some estimates come with methods for computing the confidence interval analytically, more complicated statistics, such as the AUC for example, are difficult. For these we can use a method called the <em>bootstrap</em>. The bootstrap estimates the uncertainty by resampling the dataset with replacement. For each resampling <span class="math inline">\(i\)</span>, we will get a new estimate, <span class="math inline">\(\hat{s}_i\)</span>. We can then estimate the distribution of <span class="math inline">\(\hat{s}\)</span> by using the distribution of <span class="math inline">\(\hat{s}_i\)</span> for our bootstrap samples.</p>
<p>The Bootstrap method has many advantages, one of which is that it does not assume the underlying distribution is normal.</p>
<p>In the code below, we create bootstrap samples and compute sample AUCs from those samples. Note that we use stratified random sampling (sampling from the positive and negative classes separately) to make sure that members of each class are represented.</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> bootstrap_auc(y, pred, classes, bootstraps <span class="op">=</span> <span class="dv">100</span>, fold_size <span class="op">=</span> <span class="dv">1000</span>):</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    statistics <span class="op">=</span> np.zeros((<span class="bu">len</span>(classes), bootstraps))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> c <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(classes)):</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> pd.DataFrame(columns<span class="op">=</span>[<span class="st">'y'</span>, <span class="st">'pred'</span>])</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>        df.loc[:, <span class="st">'y'</span>] <span class="op">=</span> y[:, c]</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>        df.loc[:, <span class="st">'pred'</span>] <span class="op">=</span> pred[:, c]</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>        <span class="co"># get positive examples for stratified sampling</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>        df_pos <span class="op">=</span> df[df.y <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>        df_neg <span class="op">=</span> df[df.y <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>        prevalence <span class="op">=</span> <span class="bu">len</span>(df_pos) <span class="op">/</span> <span class="bu">len</span>(df)</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(bootstraps):</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>            <span class="co"># stratified sampling of positive and negative examples</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>            pos_sample <span class="op">=</span> df_pos.sample(n <span class="op">=</span> <span class="bu">int</span>(fold_size <span class="op">*</span> prevalence), replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>            neg_sample <span class="op">=</span> df_neg.sample(n <span class="op">=</span> <span class="bu">int</span>(fold_size <span class="op">*</span> (<span class="dv">1</span><span class="op">-</span>prevalence)), replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>            y_sample <span class="op">=</span> np.concatenate([pos_sample.y.values, neg_sample.y.values])</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>            pred_sample <span class="op">=</span> np.concatenate([pos_sample.pred.values, neg_sample.pred.values])</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>            score <span class="op">=</span> roc_auc_score(y_sample, pred_sample)</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>            statistics[c][i] <span class="op">=</span> score</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> statistics</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>statistics <span class="op">=</span> bootstrap_auc(y, pred, class_labels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can compute confidence intervals from the sample statistics that we computed.</p>
<div class="cell" data-outputid="dbb0dca8-a4f2-460d-cf26-5b8d9a0e935b" data-execution_count="31">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>util.print_confidence_intervals(class_labels, statistics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Mean AUC (CI 5%-95%)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cardiomegaly</th>
      <td>0.93 (0.90-0.96)</td>
    </tr>
    <tr>
      <th>Emphysema</th>
      <td>0.93 (0.91-0.96)</td>
    </tr>
    <tr>
      <th>Effusion</th>
      <td>0.89 (0.87-0.91)</td>
    </tr>
    <tr>
      <th>Hernia</th>
      <td>0.62 (0.29-0.98)</td>
    </tr>
    <tr>
      <th>Infiltration</th>
      <td>0.70 (0.66-0.74)</td>
    </tr>
    <tr>
      <th>Mass</th>
      <td>0.89 (0.85-0.92)</td>
    </tr>
    <tr>
      <th>Nodule</th>
      <td>0.75 (0.69-0.80)</td>
    </tr>
    <tr>
      <th>Atelectasis</th>
      <td>0.79 (0.75-0.83)</td>
    </tr>
    <tr>
      <th>Pneumothorax</th>
      <td>0.83 (0.76-0.90)</td>
    </tr>
    <tr>
      <th>Pleural_Thickening</th>
      <td>0.87 (0.82-0.91)</td>
    </tr>
    <tr>
      <th>Pneumonia</th>
      <td>0.77 (0.68-0.84)</td>
    </tr>
    <tr>
      <th>Fibrosis</th>
      <td>0.80 (0.73-0.86)</td>
    </tr>
    <tr>
      <th>Edema</th>
      <td>0.86 (0.82-0.89)</td>
    </tr>
    <tr>
      <th>Consolidation</th>
      <td>0.80 (0.74-0.86)</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>As you can see, our confidence intervals are much wider for some classes than for others. Hernia, for example, has an interval around (0.30 - 0.98), indicating that we can’t be certain it is better than chance (at 0.5).</p>
</section>
<section id="precision-recall-curve" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="precision-recall-curve"><span class="header-section-number">5</span> Precision-Recall Curve</h2>
<p>Precision-Recall are informative prediction metrics when significant class imbalance are present in the data.</p>
<p>In information retrieval - Precision is a measure of result relevancy and that is equivalent to our previously defined PPV. - Recall is a measure of how many truly relevant results are returned and that is equivalent to our previously defined sensitivity measure.</p>
<p>The precision-recall curve (PRC) shows the trade-off between precision and recall for different thresholds. A high area under the curve represents both high recall and high precision, where high precision relates to a low false positive rate, and high recall relates to a low false negative rate.</p>
<p>High scores for both show that the classifier is returning accurate results (high precision), as well as returning a majority of all positive results (high recall).</p>
<div class="cell" data-outputid="c54c393a-bcc7-453f-f6ca-e0676328bd09" data-execution_count="32">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>util.get_curve(y, pred, class_labels, curve<span class="op">=</span><span class="st">'prc'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-05-22-evaluation-diagnostic-medical-models_files/figure-html/cell-27-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="f1-score" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="f1-score"><span class="header-section-number">6</span> F1 Score</h2>
<p>F1 score is the harmonic mean of the precision and recall, where an F1 score reaches its best value at 1 (perfect precision and recall) and worst at 0. The harmonic mean differs from the more common arithmetic mean, in that it gives more weight to the lower value. This means the F1 score leads to a more modest score than would be given by the arithmetic mean, which can be skewed by extremely high values.</p>
<p>Again, we can simply use <code>sklearn</code>’s utility metric function of <code>f1_score</code> to add this measure to our performance table.</p>
<div class="cell" data-outputid="c3d45590-b4dc-4f05-827b-54961bd628ff" data-execution_count="33">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> f1_score</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>util.get_performance_metrics(y, pred, class_labels, acc<span class="op">=</span>get_accuracy, prevalence<span class="op">=</span>get_prevalence, </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                        sens<span class="op">=</span>get_sensitivity, spec<span class="op">=</span>get_specificity, ppv<span class="op">=</span>get_ppv, npv<span class="op">=</span>get_npv, auc<span class="op">=</span>roc_auc_score,f1<span class="op">=</span>f1_score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>TP</th>
      <th>TN</th>
      <th>FP</th>
      <th>FN</th>
      <th>Accuracy</th>
      <th>Prevalence</th>
      <th>Sensitivity</th>
      <th>Specificity</th>
      <th>PPV</th>
      <th>NPV</th>
      <th>AUC</th>
      <th>F1</th>
      <th>Threshold</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Cardiomegaly</th>
      <td>16</td>
      <td>814</td>
      <td>169</td>
      <td>1</td>
      <td>0.83</td>
      <td>0.017</td>
      <td>0.941</td>
      <td>0.828</td>
      <td>0.086</td>
      <td>0.999</td>
      <td>0.933</td>
      <td>0.158</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Emphysema</th>
      <td>20</td>
      <td>869</td>
      <td>103</td>
      <td>8</td>
      <td>0.889</td>
      <td>0.028</td>
      <td>0.714</td>
      <td>0.894</td>
      <td>0.163</td>
      <td>0.991</td>
      <td>0.935</td>
      <td>0.265</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Effusion</th>
      <td>99</td>
      <td>690</td>
      <td>196</td>
      <td>15</td>
      <td>0.789</td>
      <td>0.114</td>
      <td>0.868</td>
      <td>0.779</td>
      <td>0.336</td>
      <td>0.979</td>
      <td>0.891</td>
      <td>0.484</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Hernia</th>
      <td>1</td>
      <td>743</td>
      <td>255</td>
      <td>1</td>
      <td>0.744</td>
      <td>0.002</td>
      <td>0.5</td>
      <td>0.744</td>
      <td>0.004</td>
      <td>0.999</td>
      <td>0.644</td>
      <td>0.008</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Infiltration</th>
      <td>114</td>
      <td>543</td>
      <td>265</td>
      <td>78</td>
      <td>0.657</td>
      <td>0.192</td>
      <td>0.594</td>
      <td>0.672</td>
      <td>0.301</td>
      <td>0.874</td>
      <td>0.696</td>
      <td>0.399</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Mass</th>
      <td>40</td>
      <td>789</td>
      <td>158</td>
      <td>13</td>
      <td>0.829</td>
      <td>0.053</td>
      <td>0.755</td>
      <td>0.833</td>
      <td>0.202</td>
      <td>0.984</td>
      <td>0.888</td>
      <td>0.319</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Nodule</th>
      <td>28</td>
      <td>731</td>
      <td>220</td>
      <td>21</td>
      <td>0.759</td>
      <td>0.049</td>
      <td>0.571</td>
      <td>0.769</td>
      <td>0.113</td>
      <td>0.972</td>
      <td>0.745</td>
      <td>0.189</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Atelectasis</th>
      <td>64</td>
      <td>657</td>
      <td>249</td>
      <td>30</td>
      <td>0.721</td>
      <td>0.094</td>
      <td>0.681</td>
      <td>0.725</td>
      <td>0.204</td>
      <td>0.956</td>
      <td>0.781</td>
      <td>0.314</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumothorax</th>
      <td>24</td>
      <td>785</td>
      <td>183</td>
      <td>8</td>
      <td>0.809</td>
      <td>0.032</td>
      <td>0.75</td>
      <td>0.811</td>
      <td>0.116</td>
      <td>0.99</td>
      <td>0.826</td>
      <td>0.201</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pleural_Thickening</th>
      <td>24</td>
      <td>713</td>
      <td>259</td>
      <td>4</td>
      <td>0.737</td>
      <td>0.028</td>
      <td>0.857</td>
      <td>0.734</td>
      <td>0.085</td>
      <td>0.994</td>
      <td>0.868</td>
      <td>0.154</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Pneumonia</th>
      <td>14</td>
      <td>661</td>
      <td>320</td>
      <td>5</td>
      <td>0.675</td>
      <td>0.019</td>
      <td>0.737</td>
      <td>0.674</td>
      <td>0.042</td>
      <td>0.992</td>
      <td>0.762</td>
      <td>0.079</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Fibrosis</th>
      <td>10</td>
      <td>725</td>
      <td>261</td>
      <td>4</td>
      <td>0.735</td>
      <td>0.014</td>
      <td>0.714</td>
      <td>0.735</td>
      <td>0.037</td>
      <td>0.995</td>
      <td>0.801</td>
      <td>0.07</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Edema</th>
      <td>15</td>
      <td>767</td>
      <td>213</td>
      <td>5</td>
      <td>0.782</td>
      <td>0.02</td>
      <td>0.75</td>
      <td>0.783</td>
      <td>0.066</td>
      <td>0.994</td>
      <td>0.856</td>
      <td>0.121</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>Consolidation</th>
      <td>36</td>
      <td>658</td>
      <td>297</td>
      <td>9</td>
      <td>0.694</td>
      <td>0.045</td>
      <td>0.8</td>
      <td>0.689</td>
      <td>0.108</td>
      <td>0.987</td>
      <td>0.799</td>
      <td>0.19</td>
      <td>0.5</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="calibration" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="calibration"><span class="header-section-number">7</span> Calibration</h2>
<p>When performing classification we often want not only to predict the class label, but also obtain a probability of each label. This probability would ideally give us some kind of confidence on the prediction. In order to observe how our model’s generated probabilities are aligned with the real probabilities, we can plot what’s called a <em>calibration curve</em>.</p>
<p>In order to generate a calibration plot, we first bucketize our predictions to a fixed number of separate bins (e.g.&nbsp;5) between 0 and 1. We then calculate a point for each bin: the x-value for each point is the mean for the probability that our model has assigned to these points and the y-value for each point fraction of true positives in that bin. We then plot these points in a linear plot. A well-calibrated model has a calibration curve that almost aligns with the y=x line.</p>
<p>The <code>sklearn</code> library has a utility <code>calibration_curve</code> for generating a calibration plot. Let’s use it and take a look at our model’s calibration:</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.calibration <span class="im">import</span> calibration_curve</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_calibration_curve(y, pred):</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">20</span>))</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(class_labels)):</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>        plt.subplot(<span class="dv">4</span>, <span class="dv">4</span>, i <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>        fraction_of_positives, mean_predicted_value <span class="op">=</span> calibration_curve(y[:,i], pred[:,i], n_bins<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>        plt.plot([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="dv">0</span>, <span class="dv">1</span>], linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>        plt.plot(mean_predicted_value, fraction_of_positives, marker<span class="op">=</span><span class="st">'.'</span>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>        plt.xlabel(<span class="st">"Predicted Value"</span>)</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>        plt.ylabel(<span class="st">"Fraction of Positives"</span>)</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>        plt.title(class_labels[i])</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="b4a496d7-032f-42e2-a31e-b4913c982a94" data-execution_count="35">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>plot_calibration_curve(y, pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-05-22-evaluation-diagnostic-medical-models_files/figure-html/cell-30-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>As the above plots show, for most predictions our model’s calibration plot does not resemble a well calibrated plot. How can we fix that?…</p>
<p>Thankfully, there is a very useful method called <a href="https://en.wikipedia.org/wiki/Platt_scaling">Platt scaling</a> which works by fitting a logistic regression model to our model’s scores. To build this model, we will be using the training portion of our dataset to generate the linear model and then will use the model to calibrate the predictions for our test portion.</p>
<div class="cell" data-scrolled="true" data-execution_count="36">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression <span class="im">as</span> LR </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> train_results[class_labels].values</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>pred_train <span class="op">=</span> train_results[pred_labels].values</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>pred_calibrated <span class="op">=</span> np.zeros_like(pred)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(class_labels)):</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>    lr <span class="op">=</span> LR(solver<span class="op">=</span><span class="st">'liblinear'</span>, max_iter<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>    lr.fit(pred_train[:, i].reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), y_train[:, i])    </span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>    pred_calibrated[:, i] <span class="op">=</span> lr.predict_proba(pred[:, i].reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>))[:,<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="2cfe338a-6a19-4b34-a189-e5126d79e252" data-execution_count="37">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>plot_calibration_curve(y[:,], pred_calibrated)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-05-22-evaluation-diagnostic-medical-models_files/figure-html/cell-32-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="conclusion" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">8</span> Conclusion</h2>
<p>In this article we covered specific metrics that are of particular relevance to evaluating models for medical diagnosis. These metrics were:</p>
<ol type="1">
<li>Accuracy</li>
<li>Prevalence</li>
<li>Specificity &amp; Sensitivity</li>
<li>PPV and NPV</li>
<li>ROC curve and AUCROC (c-statistic)</li>
<li>Confidence Intervals</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp(/http:\/\/livingdatalab\.com/);
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->



</body></html>