project:
  type: website
  output-dir: docs

website:
  title: "LivingDataLab"
  description: 'LivingDataLab Data Science Blog'
  site-url: 'http://livingdatalab.com'
  twitter-card: true
  open-graph: true
  favicon: "images/favicon.ico"
  google-analytics: "UA-91568149-1"
  margin-header: subscribe.html
  page-footer: "LivingDataLab Data Science Blog" 
  body-footer: subscribe.html
  navbar:
    logo: "images/logo.png"
    right:
      - text: "Blog"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "About"
        file: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/pranath-fernando/
      - icon: twitter
        href: https://twitter.com/LivingDataLab
      - icon: github
        href: https://github.com/pranath
      - icon: rss
        href: index.xml
  sidebar:
    - title: "Projects"
      style: "docked"
      contents: 
        - projects.qmd
        - section: Projects
          contents: projects/*
format:
  html:
    theme: flatly
    css: css/styles.css
    link-external-icon: true
    link-external-newwindow: true
